  version: "3"
  services:
    frontend:
      build: frontend
      container_name: frontend
      ports:
        - 3000:3000
      restart: always
      depends_on:
        - backend
    backend:
      build: backend
      container_name: backend
      environment:
        SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/test
      ports:
        - 8080:8080
      restart: always
      depends_on:
        - db
    db:
      image: postgres
      container_name: db
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgrespw
        - POSTGRES_DB=test
        - PGDATA=/var/lib/postgresql/data/pgdata
      ports:
        - 5432:5432
      volumes:
        - pgdata:/var/lib/postgresql/data
      restart: always
  volumes:
    pgdata: